### ISSUE TITLE
NoSuchMethodError when trying to use the reload script effect.

### ISSUE THREAD

**Issue by Snow-Pyon** [tim740/skUtilities#28]
As said in the title, I'm getting a NoSuchMethodError while trying to use the `reload script` effect. This might be due to the changes made on [this commit](https://github.com/bensku/Skript/commit/65ef8d96caf7ddd9329e1973325bf518ba614d07) as it uses Config objects rather than File objects now.

-----

Code:
```
#although it isn't really useful since the error happens no matter how you execute the effect, here is it:
on skript load:

  wait 1 second

  reload script script's name 
```

-----

Errors:
```
[18:23:15 WARN]: [Skript] Task #26 for Skript v2.2-dev29 generated an exception
java.lang.NoSuchMethodError: ch.njol.skript.ScriptLoader.loadScripts([Ljava/io/File;)Lch/njol/skript/ScriptLoader$ScriptInfo;
        at uk.tim740.skUtilities.util.EffReloadSkript.execute(EffReloadSkript.java:32) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.effects.Delay$1.run(Delay.java:94) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

-----

Versions:

Addon Version: 0.9.0
Skript Version: 2.2-dev29
Minecraft Version: 1.11.2
Java Version: 1.8.0_131b11

**Comment by aescraftbr** [comment]
can confirm.
Nice.

**Comment by tim740** [comment]
@bensku

**Comment by bensku** [comment]
I did remov some methods due to changes to internals. And even before they were removed, it was required to call another method before actually loading the script to parse function signatures.

I'll see if I can add more sane and documented API for script reloads. Also, possibly emulating old behaviour like this.

**Comment by tim740** [comment]
@bensku i suggest you add this to base skript

**Comment by bensku** [comment]
It is planned, but no ETA.
